# Machine Learning Bootcamp - Project 1

## Car Sales Price Prediction (Regression)

#### ***We'll follow this roadmap:***

1. **Load the data**
2. **Explore the data**
3. **Clean the data**
4. **Prepare the data**
6. **Build a baseline model**
7. **Compare with other models**
8. **Evaluate the model**
9. **Improve the model**
10. **Compare models**
11. **Select the best model**

In [1]:
roadmap = [
"Load the data",
"Explore the data",
"Clean the data",
"Prepare the data",
"Build a baseline model",
"Compare with other models",
"Evaluate the model",
"Improve the model",
"Compare models",
"Select the best model"
]

In [2]:
roadmap

['Load the data',
 'Explore the data',
 'Clean the data',
 'Prepare the data',
 'Build a baseline model',
 'Compare with other models',
 'Evaluate the model',
 'Improve the model',
 'Compare models',
 'Select the best model']

# SECTION 1 — Import the libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

# SECTION 2 — Load the dataset

In [4]:
car_sales = pd.read_csv("data/car-sales-extended-missing-data.csv")
car_sales

       Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

# SECTION 3 — Explore the dataset

### **1. View the first rows**

In [5]:
car_sales.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

### **2. View the last rows**

In [6]:
car_sales.tail()

       Make Colour  Odometer (KM)  Doors    Price
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

### **3. Check the shape**

In [7]:
car_sales.shape

(1000, 5)

### **4. Column names**

In [8]:
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='str')

### **5. Data types**

In [9]:
car_sales.dtypes

Make                 str
Colour               str
Odometer (KM)    float64
Doors            float64
Price            float64
dtype: object

### **6. Dataset information**

In [10]:
car_sales.dtypes

Make                 str
Colour               str
Odometer (KM)    float64
Doors            float64
Price            float64
dtype: object

### **7. Statistical summary**

In [11]:
car_sales.describe()

       Odometer (KM)       Doors         Price
count     950.000000  950.000000    950.000000
mean   131253.237895    4.011579  16042.814737
std     69094.857187    0.382539   8581.695036
min     10148.000000    3.000000   2796.000000
25%     70391.250000    4.000000   9529.250000
50%    131821.000000    4.000000  14297.000000
75%    192668.500000    4.000000  20806.250000
max    249860.000000    5.000000  52458.000000

### **8. Missing values**

In [12]:
car_sales.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

### **9. Percentage of missing values**

In [13]:
(car_sales.isna().sum() / len(car_sales)) * 100

Make             4.9
Colour           5.0
Odometer (KM)    5.0
Doors            5.0
Price            5.0
dtype: float64

### **10. Check duplicate rows**

In [14]:
car_sales.duplicated().sum()

np.int64(1)

### **11. Look at the target variable**

In [15]:
car_sales["Price"].describe()

count      950.000000
mean     16042.814737
std       8581.695036
min       2796.000000
25%       9529.250000
50%      14297.000000
75%      20806.250000
max      52458.000000
Name: Price, dtype: float64

In [16]:
roadmap

['Load the data',
 'Explore the data',
 'Clean the data',
 'Prepare the data',
 'Build a baseline model',
 'Compare with other models',
 'Evaluate the model',
 'Improve the model',
 'Compare models',
 'Select the best model']

# SECTION 2 — Data Cleaning

### **Why do we clean the data?**

Imagine you want to predict a car's price.

Your dataset looks like this:

In [17]:
car_sales.head(10)

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0
5   Honda    Red        42652.0    4.0  23883.0
6  Toyota   Blue       163453.0    4.0   8473.0
7   Honda  White            NaN    4.0  20306.0
8     NaN  White       130538.0    4.0   9374.0
9   Honda   Blue        51029.0    4.0  26683.0

#### The model asks:

**"What is the odometer reading for the Honda at index=7?"**

**Answer:**

**"I don't know."**

**Most scikit-learn models cannot train with missing values.**

**So we must handle them first.**

### **Step 1. Make a copy of the data**

***Never clean the original dataset directly.***

In [18]:
car_sales_filled = car_sales.copy() # We made this incasse of mistake, we can correct using
# the original
car_sales_filled

       Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

### **Step 2. Fill the "Make" column**

***Check how many are missing.***

In [19]:
car_sales_filled["Make"].isna().sum()

np.int64(49)

**Fill Them**

In [20]:
car_sales_filled["Make"] = car_sales_filled["Make"].fillna("Missing")
car_sales_filled["Make"].head(10)

0      Honda
1        BMW
2      Honda
3     Toyota
4     Nissan
5      Honda
6     Toyota
7      Honda
8    Missing
9      Honda
Name: Make, dtype: str

### ***We filled `Make` missing columns with `Missing` bcos `Make` is categorical, and we cannot calculate Average `Toyota and BMW`***

### **Step 3. Fill the "Colour" column**

In [21]:
car_sales_filled["Colour"] = car_sales_filled["Colour"].fillna("Missing")

### **Step 4. Fill the Odometer column**

In [22]:
car_sales_filled["Odometer (KM)"].isna().sum()

np.int64(50)

**Fill with the mean.**

In [23]:
car_sales_filled["Odometer (KM)"].mean()

np.float64(131253.23789473684)

In [24]:
car_sales_filled["Odometer (KM)"] = car_sales_filled["Odometer (KM)"].fillna(
    car_sales_filled["Odometer (KM)"].mean()
)

**Could we use the median?**

***Yes.***

***In fact, if the data has extreme outliers, median is often better.***

### **Step 5. Fill Doors**

**Look at the values:**

In [25]:
car_sales_filled["Doors"].value_counts()

Doors
4.0    811
5.0     75
3.0     64
Name: count, dtype: int64

**Most cars have 4 doors.**

In [26]:
car_sales_filled["Doors"].mode()[0]

np.float64(4.0)

***So we fill them with the mode():***

In [27]:
car_sales_filled["Doors"] = car_sales_filled["Doors"].fillna(
    car_sales_filled["Doors"].mode()[0]
)

**Why mode?**

***Doors is really a discrete category.***

***Average doors: 4.27, doesn't make much practical sense.***

***The most common value is usually a better choice.***

### **Step 6. Handle the target column**

***Look at the missing values.***

In [28]:
car_sales_filled["Price"].isna().sum()

np.int64(50)

**Question**

***Can we fill missing prices with the mean?***
***The answer is: No.***

**Why?**

***Because Price is the target (y).***

***If you invent target values, you're teaching the model with made-up answers.***

***That's a bad practice.***

***Instead, remove those rows.***

In [29]:
car_sales_filled.dropna(subset=["Price"], inplace=True)

### **Step 7. Verify everything**

In [30]:
car_sales_filled.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

**Excellent, Now the data is complete**

### **Step 8. Compare before and after**

**Original:**

In [31]:
car_sales.shape

(1000, 5)

**Filled:**

In [32]:
car_sales_filled.shape

(950, 5)

***You should notice that only the rows with missing Price were removed.***

**Everything else was preserved.***

### **Step 9. Save the cleaned dataset (Optional)**

***This is good practice.***

In [33]:
car_sales_filled.to_csv(
    "car-sales-clean.csv",
    index=False
)

## **A very important lesson**

**Many beginners memorize:**

* ***Mean***
* ***Median***
* ***Mode***

**Instead, ask yourself:  What kind of variable is this?**

* ***Categorical → Often fill with "Missing" or the mode.***
* ***Continuous numerical → Often use the mean or median.***
* ***Target variable (y) → Usually remove rows with missing targets rather than filling them.***

***If you understand why you're choosing a method, you'll be able to make good decisions on new datasets instead of relying on memorized rules.***

# Section 3 – Data Preparation

In [34]:
roadmap

['Load the data',
 'Explore the data',
 'Clean the data',
 'Prepare the data',
 'Build a baseline model',
 'Compare with other models',
 'Evaluate the model',
 'Improve the model',
 'Compare models',
 'Select the best model']

### **Step 1: Separate the Features (X) and Target (y)**

**Remember:**

***The target is what we want to predict.***

***In this dataset, we're predicting the Price.***

**So:**

In [35]:
X = car_sales_filled.drop("Price", axis=1)

y = car_sales_filled["Price"]

**Why the above?**

***Machine learning models need to know:***

* ***X → Information used to make predictions.***
* ***y → The correct answers.***

### **Step 2: Inspect X**

In [36]:
X.head()

     Make Colour  Odometer (KM)  Doors
0   Honda  White        35431.0    4.0
1     BMW   Blue       192714.0    5.0
2   Honda  White        84714.0    4.0
3  Toyota  White       154365.0    4.0
4  Nissan   Blue       181577.0    3.0

**Immediately ask yourself:**

***Can RandomForestRegressor understand words like "Toyota" and "White"?***

***Answer: No.***

***Machine learning models work with numbers, not text.***

### **Step 3: Convert Text into Numbers**

#### **We'll use One-Hot Encoding: This will convert the parts in our that are strings X to numbers i.e 1 or 0.**

In [37]:
pd.__version__

'3.0.2'

In [38]:
X = pd.get_dummies(X).astype(int)
X.head(10)

,Odometer (KM),Doors,Make_BMW,Make_Honda,Make_Missing,Make_Nissan,Make_Toyota,Colour_Black,Colour_Blue,Colour_Green,Colour_Missing,Colour_Red,Colour_White
0,35431,4,0,1,0,0,0,0,0,0,0,0,1
1,192714,5,1,0,0,0,0,0,1,0,0,0,0
2,84714,4,0,1,0,0,0,0,0,0,0,0,1
3,154365,4,0,0,0,0,1,0,0,0,0,0,1
4,181577,3,0,0,0,1,0,0,1,0,0,0,0
5,42652,4,0,1,0,0,0,0,0,0,0,1,0
6,163453,4,0,0,0,0,1,0,1,0,0,0,0
7,131253,4,0,1,0,0,0,0,0,0,0,0,1
8,130538,4,0,0,1,0,0,0,0,0,0,0,1
9,51029,4,0,1,0,0,0,0,1,0,0,0,0

### **Step 4: Check the data types**

In [39]:
X.dtypes

Odometer (KM)     int64
Doors             int64
Make_BMW          int64
Make_Honda        int64
Make_Missing      int64
Make_Nissan       int64
Make_Toyota       int64
Colour_Black      int64
Colour_Blue       int64
Colour_Green      int64
Colour_Missing    int64
Colour_Red        int64
Colour_White      int64
dtype: object

### **Step 5: Split into Training and Testing Sets**

In [40]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

**Suppose we have 950 rows after cleaning.**

**With test_size=0.2:**

* ***80% (760 rows) → Training set***
* ***20% (190 rows) → Testing set***

### **Step 6: Check the shapes**

In [41]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(760, 13)
(190, 13)
(760,)
(190,)

### **Step 7: Verify the split**

***Check the first few rows:***

In [42]:
X_train.head(10)

,Odometer (KM),Doors,Make_BMW,Make_Honda,Make_Missing,Make_Nissan,Make_Toyota,Colour_Black,Colour_Blue,Colour_Green,Colour_Missing,Colour_Red,Colour_White
986,71934,4,0,1,0,0,0,0,0,0,0,0,1
297,162665,4,0,0,0,0,1,0,0,0,0,1,0
566,42844,4,0,1,0,0,0,0,0,0,0,0,1
282,195829,4,0,1,0,0,0,0,0,0,0,0,1
109,219217,4,0,1,0,0,0,0,1,0,0,0,0
77,126669,4,0,0,1,0,0,0,0,0,0,0,1
741,76416,4,0,0,0,0,1,0,1,0,0,0,0
822,114699,4,0,0,0,1,0,0,0,0,0,0,1
82,180021,3,0,0,0,1,0,0,1,0,0,0,0
644,28561,4,0,1,0,0,0,0,1,0,0,0,0

***Then:***

In [43]:
X_test.head(10)

,Odometer (KM),Doors,Make_BMW,Make_Honda,Make_Missing,Make_Nissan,Make_Toyota,Colour_Black,Colour_Blue,Colour_Green,Colour_Missing,Colour_Red,Colour_White
203,99761,4,0,0,0,0,1,0,1,0,0,0,0
979,17975,4,0,0,0,0,1,1,0,0,0,0,0
729,197664,4,0,1,0,0,0,0,1,0,0,0,0
838,235589,4,0,0,0,1,0,0,0,1,0,0,0
919,231659,4,0,1,0,0,0,1,0,0,0,0,0
601,247601,4,0,0,0,0,1,0,1,0,0,0,0
865,110078,4,0,0,0,0,1,0,0,1,0,0,0
974,155383,4,0,0,1,0,0,0,0,0,0,0,1
509,26634,4,0,0,0,1,0,0,0,0,0,0,1
178,131253,4,0,1,0,0,0,0,0,0,0,0,1

# SECTION 4 – Build the Baseline Model

### **What is a Baseline Model?**

#### ***A baseline model is simply the first model you train using its default settings.***

***You are not trying to build the best model yet.***

***You are asking:***

***"If I use this model without trying to improve it, how well does it perform?"***

***This gives us a benchmark to compare future improvements.***

### **Step 1: Import the model**

***Since we're predicting Price, this is a regression problem.***

***We'll use a Random Forest Regressor.***

In [44]:
from sklearn.ensemble import RandomForestRegressor

### **Step 2: Create the model**

In [45]:
rf_model = RandomForestRegressor(random_state=42)

**Notice we didn't specify things like:**

* ***n_estimators***
* ***max_depth***
* ***max_features***
* ***min_samples_leaf***

***We're using the default values.***

***That's why this is called a baseline model.***

### **Step 3: Train the model**

***This is for the model to learn patterns in the data***

In [46]:
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

### **Step 4: Make predictions**

***Now ask the model to predict prices it has never seen before.***

In [47]:
y_preds = rf_model.predict(X_test)

### **Step 5: Look at the predictions**

In [48]:
y_preds[:10]

array([17596.01     , 22919.25     , 12129.12     ,  9678.06     ,
       11270.69     , 11254.7      , 15828.67     , 10419.1      ,
       18582.69     , 16148.4537568])

### **Step 6: Compare with the real prices**

In [49]:
comparison = pd.DataFrame({
    "Actual Price": y_test,
    "Predicted Price": y_preds
})

comparison.head(10)

     Actual Price  Predicted Price
203       10547.0     17596.010000
979       17940.0     22919.250000
729       12950.0     12129.120000
838        5905.0      9678.060000
919        9826.0     11270.690000
601       11162.0     11254.700000
865       13650.0     15828.670000
974       14345.0     10419.100000
509       12024.0     18582.690000
178       10076.0     16148.453757

**Notice:**

***They are close, but not exactly equal.***

***That is perfectly normal.***

### **Step 7: Evaluate the model**

**Now we answer the most important question:**

***How good is this model?***

***Import the metrics.***

In [50]:
from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error
)

* ***i) R² Score***

In [51]:
r2 = r2_score(y_test, y_preds)

print(r2)

0.2128085605802793

* ***ii) MAE***

In [52]:
mae = mean_absolute_error(y_test, y_preds)

print(mae)

5790.00159462482

***The Interpretation is that on Avg. the prediction is about $5790 away from the true price***

* ***iii)MSE***

In [53]:
mse = mean_squared_error(y_test, y_preds)

print(mse)

52710097.128180124

***Large errors are penalized more than small ones.***

* ***iv) RMSE***

In [54]:
rmse = np.sqrt(mse)

print(rmse)

7260.1719764878935

***Interpretation: Typically, your predictions differ from the true prices by about $7260***

### **Step 8: Print everything neatly**

In [55]:
print(f"R² Score : {r2:.3f}")
print(f"MAE      : {mae:.2f}")
print(f"MSE      : {mse:.2f}")
print(f"RMSE     : {rmse:.2f}")

R² Score : 0.213
MAE      : 5790.00
MSE      : 52710097.13
RMSE     : 7260.17

### **Step 9: Save the results**

***We'll use these later when comparing models.***

In [56]:
baseline_results = {
    "Model": "Random Forest",
    "R²": r2,
    "MAE": mae,
    "MSE": mse,
    "RMSE": rmse
}

In [57]:
roadmap

['Load the data',
 'Explore the data',
 'Clean the data',
 'Prepare the data',
 'Build a baseline model',
 'Compare with other models',
 'Evaluate the model',
 'Improve the model',
 'Compare models',
 'Select the best model']

# SECTION 5 – Compare Different Regression Models

### **Goal:**
**Train four different models on the same training data and compare them using the same evaluation metrics.**

**The models are:**

* ***Linear Regression***
* ***Decision Tree Regressor***
* ***Random Forest Regressor***
* ***KNN Regressor***

### **Step 1: Import the models**

In [58]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor

### **Step 2: Create the models**

***Instead of creating them one by one, store them in a dictionary.***

In [59]:
models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(random_state=42),
    "KNN": KNeighborsRegressor()
}

### **Step 3: Create an empty list**

***We'll save each model's results here.***

In [60]:
results = []

### **Step 4: Train and evaluate every model**

In [61]:
from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error
)

for name, model in models.items():

    # Train the model
    model.fit(X_train, y_train)

    # Make predictions
    y_preds = model.predict(X_test)

    # Evaluate
    r2 = r2_score(y_test, y_preds)
    mae = mean_absolute_error(y_test, y_preds)
    mse = mean_squared_error(y_test, y_preds)
    rmse = np.sqrt(mse)

    # Store results
    results.append({
        "Model": name,
        "R²": r2,
        "MAE": mae,
        "MSE": mse,
        "RMSE": rmse
    })

### **Step 5: Create a comparison table**

In [62]:
comparison = pd.DataFrame(results)
comparison

               Model        R²          MAE           MSE         RMSE
0  Linear Regression  0.253275  5716.417805  5.000049e+07  7071.102123
1      Decision Tree -0.343441  7320.128070  8.995643e+07  9484.536317
2      Random Forest  0.212809  5790.001595  5.271010e+07  7260.171976
3                KNN  0.021323  6216.727368  6.553193e+07  8095.179510

### **Step 6: Sort by R²**

***The one having highest R² will be on top***

In [63]:
comparison.sort_values("R²", ascending=False)

               Model        R²          MAE           MSE         RMSE
0  Linear Regression  0.253275  5716.417805  5.000049e+07  7071.102123
2      Random Forest  0.212809  5790.001595  5.271010e+07  7260.171976
3                KNN  0.021323  6216.727368  6.553193e+07  8095.179510
1      Decision Tree -0.343441  7320.128070  8.995643e+07  9484.536317

### **Step 7: Sort by MAE**

In [64]:
comparison.sort_values("MAE")

               Model        R²          MAE           MSE         RMSE
0  Linear Regression  0.253275  5716.417805  5.000049e+07  7071.102123
2      Random Forest  0.212809  5790.001595  5.271010e+07  7260.171976
3                KNN  0.021323  6216.727368  6.553193e+07  8095.179510
1      Decision Tree -0.343441  7320.128070  8.995643e+07  9484.536317

### **Step 8: Sort by RMSE**

In [65]:
comparison.sort_values("RMSE")

               Model        R²          MAE           MSE         RMSE
0  Linear Regression  0.253275  5716.417805  5.000049e+07  7071.102123
2      Random Forest  0.212809  5790.001595  5.271010e+07  7260.171976
3                KNN  0.021323  6216.727368  6.553193e+07  8095.179510
1      Decision Tree -0.343441  7320.128070  8.995643e+07  9484.536317

# SECTION 6 – Cross Validation

### **What is Cross Validation?**

***Up until now you've done: `train_test_split(test_size=0.2)`***

***which produces one train/test split.***

### **The problem is:**

***What if those 200 test rows happened to be easier (or harder) than average?***

***Your evaluation could be misleading.***

***Cross-validation solves this by creating multiple train/test splits.***

### **Step 1: Import**

In [66]:
from sklearn.model_selection import cross_val_score

### **Step 2: Perform Cross Validation**

***We'll use the four models again.***

In [67]:
models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(random_state=42),
    "KNN": KNeighborsRegressor()
}

### **Step 3: Create an empty list**

In [68]:
cv_results = []

### **Step 4: Calculate CV R²**

In [69]:
for name, model in models.items():

    scores = cross_val_score(
        model,
        X,
        y,
        cv=5,
        scoring="r2"
    )

    cv_results.append({
        "Model": name,
        "Average CV R²": scores.mean(),
        "Std Dev": scores.std()
    })

***Because cross-validation automatically splits the entire dataset into training and testing folds.***

***You don't pass X_train and X_test separately.***

### **Step 5: View the results**

In [70]:
cv_results = pd.DataFrame(cv_results)

cv_results

               Model  Average CV R²   Std Dev
0  Linear Regression       0.322453  0.052249
1      Decision Tree      -0.235816  0.207705
2      Random Forest       0.228795  0.068664
3                KNN       0.025121  0.053707

### **How to interpret this**

**Average CV R²**

***This is the average R² across all five folds.***

***Higher is better.***

### **Standard Deviation**

***This tells you how stable the model is.***

***Example:***

**Model A: 0.60, 0.61, 0.59, 0.60, 0.61**

**Std Dev = 0.008 -> Very stable**

**Model B: 0.85, 0.30, 0.77, 0.15, 0.62**

**Std Dev: 0.28 -> Very unstable.**

***A lower standard deviation generally means the model is more consistent across different splits.***

***Comparing with earlier result:***

In [71]:
comparison

               Model        R²          MAE           MSE         RMSE
0  Linear Regression  0.253275  5716.417805  5.000049e+07  7071.102123
1      Decision Tree -0.343441  7320.128070  8.995643e+07  9484.536317
2      Random Forest  0.212809  5790.001595  5.271010e+07  7260.171976
3                KNN  0.021323  6216.727368  6.553193e+07  8095.179510

### AND

In [72]:
cv_results

               Model  Average CV R²   Std Dev
0  Linear Regression       0.322453  0.052249
1      Decision Tree      -0.235816  0.207705
2      Random Forest       0.228795  0.068664
3                KNN       0.025121  0.053707

## **Linear Regression from `cross_val_score` won with higher `R² of 0.32245` better than the initial**

# **SECTION 7 – Hyperparameter Tuning**

### **Since Linear Regression won, you might think we should tune it.***

#### **Here's something important:**

##### ***Linear Regression has almost no hyperparameters worth tuning.***

##### ***So `RandomizedSearchCV` and `GridSearchCV` are generally not useful for a basic LinearRegression.***

**Instead, hyperparameter(`using RandomizedSearchCV and GridSearchCV`) tuning is much more valuable for models like:**

* ***Decision Tree***
* ***Random Forest***
* ***KNN***
* ***SVM***

***So, as a learning exercise, we'll tune Random Forest.***

## **A) RandomizedSearchCV**

### **Step 1: Import**

In [73]:
from sklearn.model_selection import RandomizedSearchCV

### **Step 2: Create a parameter grid**

In [74]:
rf_grid = {
    "n_estimators": [100, 200, 500, 1000],
    "max_depth": [None, 5, 10, 20],
    "max_features": ["sqrt", "log2"],
    "min_samples_split": [2, 4, 6],
    "min_samples_leaf": [1, 2, 4]
}

### **Step 3: Create the model**

In [75]:
rf = RandomForestRegressor(random_state=42)

### **Step 4: Create RandomizedSearchCV**

In [76]:
rs_rf = RandomizedSearchCV(
    estimator=rf, # estimator the model to tune.
    param_distributions=rf_grid, # param_distributions → possible values to try
    n_iter=20,  # n_iter=20 → test 20 random combinations.
    cv=5,  # cv=5 → each combination is evaluated with 5-fold cross-validation.
    verbose=2,  # verbose=2 → show progress.
    random_state=42,  # n_jobs=-1 → use all CPU cores.
    n_jobs=-1  # random_state=42 → reproducible search.
)

### **Step 5: Fit**

In [77]:
rs_rf.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'max_depth': [None, 5, 10, 20],
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 4, 6],
                                        'n_estimators': [100, 200, 500, 1000]},
                   random_state=42, verbose=2)

***The above might take a while depending on ur computer***

### **Step 6: Best parameters**

In [78]:
rs_rf.best_params_

{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 5}

### **Step 7: Best model**

In [79]:
best_rf = rs_rf.best_estimator_
best_rf

RandomForestRegressor(max_depth=5, max_features='sqrt', n_estimators=1000,
                      random_state=42)

### **Step 8: Evaluate the tuned model**

In [80]:
y_preds = best_rf.predict(X_test)

print("R² :", r2_score(y_test, y_preds))
print("MAE:", mean_absolute_error(y_test, y_preds))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_preds)))

R² : 0.29155763269615576
MAE: 5683.416761989607
RMSE: 6887.4584161376215

### **An important lesson**

**One of the biggest lessons in machine learning is:**

***Never assume a more complex model is better. Test it.***

***Sometimes a simple Linear Regression beats a Random Forest.***

***Sometimes a tuned Random Forest beats everything else.***

***The only reliable way to know is to measure and compare, just as you've been doing throughout this project.***

In [81]:
roadmap

['Load the data',
 'Explore the data',
 'Clean the data',
 'Prepare the data',
 'Build a baseline model',
 'Compare with other models',
 'Evaluate the model',
 'Improve the model',
 'Compare models',
 'Select the best model']

# SECTION 8 - GridSearchCV

### **Why use GridSearchCV after RandomizedSearchCV?**
**Think of it this way.**

***Suppose you're looking for the highest mountain.***
* ***RandomizedSearchCV flies over the country and identifies the highest mountain range.***
* ***GridSearchCV hikes around that mountain range to find the exact highest peak.***

**Since your RandomizedSearchCV found the below as best_params_:**

***{
'n_estimators': 1000,
'min_samples_split': 2,
'min_samples_leaf': 1,
    'max_features': 'sqrt',
    'max_depth': 5
}***

#### ***We'll search around these above values***

### **Step 1: Import GridSearchCV**

In [82]:
from sklearn.model_selection import GridSearchCV

### **Step 2: Create a smaller parameter grid**
***Notice we don't search huge ranges again.***

In [83]:
grid = {
    "n_estimators": [800, 1000, 1200],
    "max_depth": [4, 5, 6],
    "max_features": ["sqrt"],
    "min_samples_split": [2, 3],
    "min_samples_leaf": [1, 2]
}

**Let's calculate how many combinations this is:**

* ***n_estimators → 3***
* ***max_depth → 3*** 
* ***max_features → 1***
* ***min_samples_split → 2***
* ***min_samples_leaf → 2***

**Total:**

***3 × 3 × 1 × 2 × 2 = 36 combinations***

**With cv=5:**

***36 × 5 = 180 model fits***

**This is manageable.**

### **Step 3: Create the model**

In [84]:
rf = RandomForestRegressor(random_state=42)

### **Step 4: Create GridSearchCV**

In [85]:
gs_rf = GridSearchCV(
    estimator=rf,
    param_grid=grid,
    cv=5,
    verbose=2,
    n_jobs=-1
)

### **Step 5: Fit**

In [86]:
gs_rf.fit(X_train, y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

GridSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [4, 5, 6], 'max_features': ['sqrt'],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 3],
                         'n_estimators': [800, 1000, 1200]},
             verbose=2)

***This will take a few minutes.This will take a few minutes.***

### **Step 6: Best parameters**

In [87]:
gs_rf.best_params_

{'max_depth': 6,
 'max_features': 'sqrt',
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 800}

### **Step 7: Best estimator**

In [88]:
best_grid_rf = gs_rf.best_estimator_

### **Step 8: Predict**

In [89]:
y_preds = best_grid_rf.predict(X_test)

### **Step 9: Evaluate**

In [90]:
from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error
)

r2 = r2_score(y_test, y_preds)
mae = mean_absolute_error(y_test, y_preds)
mse = mean_squared_error(y_test, y_preds)
rmse = np.sqrt(mse)

print(f"R²   : {r2:.3f}")
print(f"MAE  : {mae:.2f}")
print(f"MSE  : {mse:.2f}")
print(f"RMSE : {rmse:.2f}")

R²   : 0.284
MAE  : 5685.23
MSE  : 47976479.24
RMSE : 6926.51

### **Step 10: Final Comparison**
***Now create one final comparison table.***

In [91]:
final_results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Decision Tree",
        "Random Forest",
        "RandomizedSearchCV RF",
        "GridSearchCV RF"
    ],
    "R²": [
        0.253275,
        -0.343441,
        0.212809,
        0.291558,
        r2
    ],
    "MAE": [
        5716.42,
        7320.13,
        5790.00,
        5683.42,
        mae
    ],
    "RMSE": [
        7071.10,
        9484.54,
        7260.17,
        6887.46,
        rmse
    ]
})

final_results.sort_values("R²", ascending=False)

                   Model        R²         MAE         RMSE
3  RandomizedSearchCV RF  0.291558  5683.42000  6887.460000
4        GridSearchCV RF  0.283502  5685.22655  6926.505558
0      Linear Regression  0.253275  5716.42000  7071.100000
2          Random Forest  0.212809  5790.00000  7260.170000
1          Decision Tree -0.343441  7320.13000  9484.540000