# 004 NumPy DataTypes and Attributes

In [2]:
import numpy as np

## DataTypes & Attributes

## Numpy's main datatype is ndarray(which is n-dirrectional array). which can be a list of numbers u can imagine

In [3]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
               [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

## Attributes Associated with Numpy Arrays

In [8]:
# 1) shape
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
# 2) ndim: This is n-dimension
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
# 3) dtype
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
# 4) size
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
# 5) type()
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Creating a Dataframe from a Numpy array

In [14]:
import pandas as pd

df = pd.DataFrame(a2)
df

     0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# 005 Creating NumPy Arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
# 1) ones(): Return a new array of given shape and type, filled with ones.
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones.dtype

dtype('float64')

In [18]:
type(ones)

numpy.ndarray

In [19]:
# 2) zeros(): Return a new array of given shape and type, filled with zeros.
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
# 3) arange(): Return evenly spaced val ues within a given interval.
# arange(start, stop, step)
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [15]:
# 4) random()
# random(start, stop, size)
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[5, 7, 9, 7, 3],
       [9, 9, 2, 5, 3],
       [3, 9, 1, 3, 1]], dtype=int32)

In [22]:
random_array.size

15

In [23]:
random_array.shape

(3, 5)

In [24]:
random_array1 = np.random.random((5, 3))
random_array1

array([[0.15788764, 0.83107655, 0.6667729 ],
       [0.89186453, 0.69784674, 0.0449371 ],
       [0.70082526, 0.152553  , 0.60443   ],
       [0.84096127, 0.76137352, 0.45737443],
       [0.19699434, 0.52808629, 0.62701951]])

In [25]:
random_array2 = np.random.rand(5, 3)
random_array2

array([[0.25442711, 0.95077657, 0.06095086],
       [0.45828784, 0.59070037, 0.81584857],
       [0.90449675, 0.18586429, 0.96475258],
       [0.87802291, 0.62399141, 0.24170496],
       [0.67465535, 0.87913725, 0.8162063 ]])

## 006 NumPy Random Seed

In [26]:
random_array3 = np.random.randint(10, size=(5, 3))
random_array3

array([[7, 7, 2],
       [4, 8, 8],
       [0, 5, 9],
       [5, 8, 0],
       [5, 8, 0]], dtype=int32)

### Random Seed

In [27]:
# Pseudo-random numbers
# Now, each time u run the above cell "random_array3", it gives us difft outcome. What if we 
# want to share our notebook and want these figures in these "introduction-to-numpy" to be the 
# same without change of figure each time we run the cells, especially those that have 
# "ramdom.randint" etc. Thats where we need "np.random.seed()" to generate random numbers that 
# are reproducable.
np.random.seed(seed=0) # seed=0 or seed=5767 or any number will still do the samething.
random_array4 = np.random.randint(10, size=(5, 3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [28]:
np.random.seed(seed=0)
random_array5 = np.random.random((5, 3))
random_array5

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

## 007 Viewing Arrays and Matrices

In [29]:
 # B4 going forward, let's see how we can find unique elements in a numpy array
random_array6 = np.random.randint(10, size=(5, 3))
random_array6

array([[9, 4, 3],
       [0, 3, 5],
       [0, 2, 3],
       [8, 1, 3],
       [3, 3, 7]], dtype=int32)

In [30]:
np.unique(random_array6)

array([0, 1, 2, 3, 4, 5, 7, 8, 9], dtype=int32)

### Viewing Arrays and Matrices

In [31]:
 a1

array([1, 2, 3])

In [32]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [33]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [34]:
a1[0]

np.int64(1)

In [35]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
a2[1]

array([4. , 5. , 6.5])

In [37]:
a3[:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [38]:
a3[:2, :2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [39]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [40]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[0, 1, 9, 9, 0],
         [4, 7, 3, 2, 7],
         [2, 0, 0, 4, 5],
         [5, 6, 8, 4, 1]],

        [[4, 9, 8, 1, 1],
         [7, 9, 9, 3, 6],
         [7, 2, 0, 3, 5],
         [9, 4, 4, 6, 4]],

        [[4, 3, 4, 4, 8],
         [4, 3, 7, 5, 5],
         [0, 1, 5, 9, 3],
         [0, 5, 0, 1, 2]]],


       [[[4, 2, 0, 3, 2],
         [0, 7, 5, 9, 0],
         [2, 7, 2, 9, 2],
         [3, 3, 2, 3, 4]],

        [[1, 2, 9, 1, 4],
         [6, 8, 2, 3, 0],
         [0, 6, 0, 6, 3],
         [3, 8, 8, 8, 2]],

        [[3, 2, 0, 8, 8],
         [3, 8, 2, 8, 4],
         [3, 0, 4, 3, 6],
         [9, 8, 0, 8, 5]]]], dtype=int32)

In [41]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [42]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[0, 1, 9, 9],
         [4, 7, 3, 2],
         [2, 0, 0, 4],
         [5, 6, 8, 4]],

        [[4, 9, 8, 1],
         [7, 9, 9, 3],
         [7, 2, 0, 3],
         [9, 4, 4, 6]],

        [[4, 3, 4, 4],
         [4, 3, 7, 5],
         [0, 1, 5, 9],
         [0, 5, 0, 1]]],


       [[[4, 2, 0, 3],
         [0, 7, 5, 9],
         [2, 7, 2, 9],
         [3, 3, 2, 3]],

        [[1, 2, 9, 1],
         [6, 8, 2, 3],
         [0, 6, 0, 6],
         [3, 8, 8, 8]],

        [[3, 2, 0, 8],
         [3, 8, 2, 8],
         [3, 0, 4, 3],
         [9, 8, 0, 8]]]], dtype=int32)

In [43]:
a4[:, :, :, :3]

array([[[[0, 1, 9],
         [4, 7, 3],
         [2, 0, 0],
         [5, 6, 8]],

        [[4, 9, 8],
         [7, 9, 9],
         [7, 2, 0],
         [9, 4, 4]],

        [[4, 3, 4],
         [4, 3, 7],
         [0, 1, 5],
         [0, 5, 0]]],


       [[[4, 2, 0],
         [0, 7, 5],
         [2, 7, 2],
         [3, 3, 2]],

        [[1, 2, 9],
         [6, 8, 2],
         [0, 6, 0],
         [3, 8, 8]],

        [[3, 2, 0],
         [3, 8, 2],
         [3, 0, 4],
         [9, 8, 0]]]], dtype=int32)

In [44]:
a4[:, :, :, :2]

array([[[[0, 1],
         [4, 7],
         [2, 0],
         [5, 6]],

        [[4, 9],
         [7, 9],
         [7, 2],
         [9, 4]],

        [[4, 3],
         [4, 3],
         [0, 1],
         [0, 5]]],


       [[[4, 2],
         [0, 7],
         [2, 7],
         [3, 3]],

        [[1, 2],
         [6, 8],
         [0, 6],
         [3, 8]],

        [[3, 2],
         [3, 8],
         [3, 0],
         [9, 8]]]], dtype=int32)

In [45]:
a4[0]

array([[[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]],

       [[4, 3, 4, 4, 8],
        [4, 3, 7, 5, 5],
        [0, 1, 5, 9, 3],
        [0, 5, 0, 1, 2]]], dtype=int32)

In [46]:
a4[:, :, :, :2]

array([[[[0, 1],
         [4, 7],
         [2, 0],
         [5, 6]],

        [[4, 9],
         [7, 9],
         [7, 2],
         [9, 4]],

        [[4, 3],
         [4, 3],
         [0, 1],
         [0, 5]]],


       [[[4, 2],
         [0, 7],
         [2, 7],
         [3, 3]],

        [[1, 2],
         [6, 8],
         [0, 6],
         [3, 8]],

        [[3, 2],
         [3, 8],
         [3, 0],
         [9, 8]]]], dtype=int32)

In [47]:
a4[0][0]

array([[0, 1, 9, 9, 0],
       [4, 7, 3, 2, 7],
       [2, 0, 0, 4, 5],
       [5, 6, 8, 4, 1]], dtype=int32)

In [48]:
a4[:, :, :, :1]

array([[[[0],
         [4],
         [2],
         [5]],

        [[4],
         [7],
         [7],
         [9]],

        [[4],
         [4],
         [0],
         [0]]],


       [[[4],
         [0],
         [2],
         [3]],

        [[1],
         [6],
         [0],
         [3]],

        [[3],
         [3],
         [3],
         [9]]]], dtype=int32)

In [49]:
a4[0][1]

array([[4, 9, 8, 1, 1],
       [7, 9, 9, 3, 6],
       [7, 2, 0, 3, 5],
       [9, 4, 4, 6, 4]], dtype=int32)

In [50]:
a4

array([[[[0, 1, 9, 9, 0],
         [4, 7, 3, 2, 7],
         [2, 0, 0, 4, 5],
         [5, 6, 8, 4, 1]],

        [[4, 9, 8, 1, 1],
         [7, 9, 9, 3, 6],
         [7, 2, 0, 3, 5],
         [9, 4, 4, 6, 4]],

        [[4, 3, 4, 4, 8],
         [4, 3, 7, 5, 5],
         [0, 1, 5, 9, 3],
         [0, 5, 0, 1, 2]]],


       [[[4, 2, 0, 3, 2],
         [0, 7, 5, 9, 0],
         [2, 7, 2, 9, 2],
         [3, 3, 2, 3, 4]],

        [[1, 2, 9, 1, 4],
         [6, 8, 2, 3, 0],
         [0, 6, 0, 6, 3],
         [3, 8, 8, 8, 2]],

        [[3, 2, 0, 8, 8],
         [3, 8, 2, 8, 4],
         [3, 0, 4, 3, 6],
         [9, 8, 0, 8, 5]]]], dtype=int32)

In [51]:
a4[0][0][0][0]

np.int32(0)

In [52]:
a4[0][0][1][0]

np.int32(4)

In [53]:
a4[0][0][1][1]

np.int32(7)

# 008 Manipulating Arrays

## Arithmetic

In [54]:
a1

array([1, 2, 3])

In [55]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [56]:
a1 + ones

array([2., 3., 4.])

In [57]:
a1 - ones

array([0., 1., 2.])

In [58]:
a1 * ones

array([1., 2., 3.])

In [59]:
 a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [60]:
a1

array([1, 2, 3])

In [61]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [62]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3)

In [ ]:
a1 / ones

In [ ]:
a2 / a1

In [ ]:
# Floor division removes the decimals
a2 // a1

In [ ]:
 a2 ** 2

In [ ]:
np.square(a2)

In [ ]:
np.add(a1, ones)

In [ ]:
a1 % 2

In [ ]:
a1 / 2

In [ ]:
a2 % 2

In [ ]:
np.exp(a1)

In [ ]:
np.log(a1)

# 009 Manipulating Arrays 2

## Aggregation

Aggregation is performing the same operation on a number of things

In [ ]:
listy_list = [1, 2, 3]
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
sum(a1)

In [ ]:
np.sum(a1)

### Detremining which sum mthd to use

###### Use Python's mthd on Python datatypes i.e (sum()) and,

###### Use Numpy's mthd on Numpy arrays i.e (np.sum())

In [ ]:
massive_array = np.random.random(100000)
massive_array.size

In [ ]:
massive_array[:10] # Viewing the first 10

In [ ]:
# %timeit is a magic fc in jupyter notebook or python fc
# This will time the process we perform

%timeit sum(massive_array) # Python 's sum()
%timeit np.sum(massive_array) # Numpy's np.sum()

In [ ]:
# 21.2ms to micro = 21.2 * 1000 = 21200μs
21200 / 107

##### From the above results, we can see that Numpy's sum is faster than pythons sum bcos Numpy's sum() is "198.1308 times" faster than Python's sum(). So this means any arithmetic we want to do, we should use the one that is common to that mthd i.e Python's mthd on Python datatypes OR Numpy's mthd on Numpy arrays

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

In [ ]:
# Standard deviation is a measure of how spread out a grp of numbers is from the mean. 
# standard deviation = sqrt of variance
np.std(a2)

In [ ]:
# Variance is the measure to the avg. degree to which each no. is difft from the mean 
# Higher variance = wider range of numbers
# Lower vvariance = lower range of numbers
np.var(a2)

# 010 Standard Deviation and Variance

### Demo of std and var

In [ ]:
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline 
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

# 011 Reshape and Transpose

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a3

In [ ]:
# Remember in this part "008 Manipulating Arrays", we tried multiplying a2 by a3, and we got 
# an error as seen below i.e
a2 * a3

The beautiful thing about Numpy arrays is that they can be reshaped or transposed

1) reshape(): Returns an array containing the same data with a new shape.

In [ ]:
a2.shape

In [ ]:
a2.reshape(2, 3, 1).shape

In [ ]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape

In [ ]:
a2_reshape * a3

2) Transpose: This switches the axis

In [ ]:
a2.shape

In [63]:
a2.T.shape

(3, 2)

In [64]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [65]:
a3.T.shape

(3, 3, 2)

# 012 Dot Product vs Element Wise

##### This part tells us when should we use the reshape and transpose mthds

### Dot Product: This is used when transposing a matrix

In [66]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [67]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [68]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

#### 1) Element-wise multiplication (Hadamard product)

In [69]:
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]], dtype=int32)

#### 2) Dot product

In [70]:
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [71]:
# To be able to solve the above, we will need to transpose one of the matrices
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]], dtype=int32)

In [72]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [73]:
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)

# 013 Exercise Nut Butter Store Sales

### Dot product example (nut butter sales)

In [74]:
np.random.seed(0)
#1) Number of jars sold
sales_amounts = np.random.randint(20, size=(5, 3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [75]:
#2) Creating a weekly_sales dataframe
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

       Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [76]:
#3) Create prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [77]:
# 4) Create butter_prices dataframe
# without prices.reshape(1, 3), we will get an error below
butter_prices = pd.DataFrame(prices.reshape(1, 3), index=["Price"], 
                             columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

       Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [78]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [79]:
prices

array([10,  8, 12])

In [80]:
total_sales = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [81]:
prices.shape, sales_amounts.shape

((3,), (5, 3))

In [82]:
# Shapes aren't aligned, hence we need to transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [83]:
# Creating daily sales as a column
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [84]:
weekly_sales.T.shape

(3, 5)

In [1]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

NameError: name 'butter_prices' is not defined

In [ ]:
# Putting the daily_sales as a column by the right side of our dataframe
# This does not work bcos its not the right shape
weekly_sales["Total ($)"] = daily_sales
weekly_sales

In [2]:
#This works now bcos its right shape bcos of the transpose
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

NameError: name 'daily_sales' is not defined

# 014 Comparison Operators

In [87]:
a1

array([1, 2, 3])

In [88]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [89]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [90]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [91]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [92]:
a1 > 5

array([False, False, False])

In [93]:
a1 < 5

array([ True,  True,  True])

In [94]:
a1 == a1

array([ True,  True,  True])

In [95]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

# 015 Sorting Arrays

In [96]:
random_array

array([[8, 3, 5, 1, 6],
       [7, 4, 6, 7, 5],
       [8, 4, 7, 9, 7]], dtype=int32)

In [97]:
# 1) sort(): Return a sorted copy of an array.
np.sort(random_array)

array([[1, 3, 5, 6, 8],
       [4, 5, 6, 7, 7],
       [4, 7, 7, 8, 9]], dtype=int32)

In [98]:
random_array

array([[8, 3, 5, 1, 6],
       [7, 4, 6, 7, 5],
       [8, 4, 7, 9, 7]], dtype=int32)

In [99]:
# 2) argsort(): : Returns the indices that would sort an array.
np.argsort(random_array)

array([[3, 1, 2, 4, 0],
       [1, 4, 2, 0, 3],
       [1, 2, 4, 0, 3]])

In [100]:
a1

array([1, 2, 3])

In [101]:
np.argsort(a1)

array([0, 1, 2])

In [102]:
# 3) argmin(): Returns the indices of the minimum values along an axis.
np.argmin(a1)

np.int64(0)

In [103]:
# 4) argmax(): Returns the indices of the maximum values along an axis.
np.argmax(a1)

np.int64(2)

In [104]:
random_array

array([[8, 3, 5, 1, 6],
       [7, 4, 6, 7, 5],
       [8, 4, 7, 9, 7]], dtype=int32)

In [105]:
np.argmax(random_array, axis=0)

array([0, 1, 2, 2, 2])

In [106]:
np.argmax(random_array, axis=1)

array([0, 0, 3])

# 016 Turn Images Into NumPy Arrays

#### So remember we talked about this right at the start with NumPy, that in machine learnming,take whatever data u have, turn it into numbers, u use a ML algorithm to find patterns in those numbers.

#### So what if ur data happens to beimages and u wanted to find out information about those images

<img src="images/panda.png" />

In [109]:
# We want to turn an image into a NumPy array, so we can use this to find patterns
from matplotlib.image import imread
panda = imread("images/panda.png")
type(panda)

numpy.ndarray

In [114]:
panda.size, panda.shape, panda.ndim
# The arrays gotten are the pixel values of colour contained in the panda image

(24465000, (2330, 3500, 3), 3)

In [113]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16862746, 0.13333334, 0.09803922],
        [0.16862746, 0.13333334, 0.09803922],
        [0.16862746, 0.13333334, 0.09803922]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16862746, 0.13333334, 0.09803922],
        [0.16862746, 0.13333334, 0.09803922],
        [0.16862746, 0.13333334, 0.09803922]]],
      shape=(5, 3500, 3), dtype=float32)

<img src="images/car-photo.png" />

In [115]:
car = imread("images/car-photo.png")
type(car)

numpy.ndarray

In [116]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]],
      shape=(1, 575, 4), dtype=float32)

In [ ]:
dog = imread("images/dog-photo.png")